### ISSUE TITLE
Определение козыря

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/Durak#5]
Написать функцию, которая определяет козырь для данной игры

**Comment by MykhayloSharapov** [comment]
```
suits = ['S','C','D','H']
import random
t = random.randint (0,3)
trump = suits [t]
```

**Comment by olegtarasenko** [comment]
We build a functions so this could work:
def trump():
    t=random.randint(0,3)
    trump = SUITS[t]
    return trump
print(trump())
